name: rcw86

channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - sunpy
    - drms
    - zeep
    - ruffus
    - boto3
    - requests
    - astropy
    - anaconda
    - numpy
    - pandas
    - bs4
    - scipy
    - sklearn
    - seaborn
    - sunpy
    - astropy
    - matplotlib
    - datetime
    - jupyter_contrib_nbextensions
    - IPython
    - scipy
    - git+https://github.com/i4Ds/IRISreader.git@master
    - jupyterlab
    - jupyterlab-git
    - sqlalchemy
    - scikit-image
